# An example of the most basic config file we can use with `MKDocs`
# Great place to start to see if this is working / what you need to fix
# or customzie

site_name: ThreadTheTTRPG
site_url: https://dezzidez.github.io/ThreadTTRPG/
site_author: DezziDez
site_description: A Table Top Role Playing System
